#! /bin/sh

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

bspc monitor -d 0 1 2 3 4 5 6 7 8

bspc config border_width         0
bspc config window_gap           8
bspc config top_padding          40

bspc config split_ratio          0.52
bspc config ignore_ewmh_struts   true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  8

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox:Toolkit sticky=on state=floating
bspc rule -a obs state=floating
bspc rule -a kitty-cava state=floating manage=on layer=below sticky=on private=on locked=on

# Load session
. "$BSPWM_CONFIG/restore.cfg"
if [ -e "$BSPWM_STATE" ] ; then
	bspc wm --load-state "$BSPWM_STATE"
	bspc wm --adopt-orphans
	rm "$BSPWM_STATE"
fi

# Autostart
"$BSPWM_CONFIG/autostart" &
